name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set SonarScanner Path
        shell: cmd
        run: |
          SET PATH=C:\Users\balamurugan.kaliyapp\Documents\SonarCLIScanner\sonar-scanner-5.0.1.3006-windows\bin;%PATH%
          echo %PATH%  # Debugging step to check if the path is set correctly

      - name: Run SonarQube Scanner
        shell: cmd
        run: |
          sonar-scanner ^
          -Dsonar.projectKey=TEST_AI ^
          -Dsonar.sources=. ^
          -Dsonar.host.url=https://panpsourceuat.ent.cgi.com/sonar/ ^
          -Dsonar.login=sqa_47073fd7cd44d214a50e771e3cbe9376199008c4 ^
          -Dsonar.language=java ^
          -X
